sudo: false
language: cpp
dist: focal

matrix:
  include:
    - name: "Linux Clang"
      os: linux
      dist: focal
      compiler: clang
      services:
        - xvfb
      addons:
        apt:
          packages:
            - clang-8
            - libsdl2-dev
            - python3-dev
            - glslang-tools

      before_install:
        - eval "CC=clang-8 && CXX=clang++-8"
      script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
        - ./testNeko/Neko_TEST
        - ./testAer/Aer_TEST
    - name: "Windows"
      os: windows
      services:
        - xvfb
      env:
        - CMAKE_PATH="/c/Program Files/CMake/bin"
        - MSBUILD_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
      before_install:
        - choco install python
        - choco install vulkan-sdk
      install:
        - choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
      script:
        - export SDL_VIDEODRIVER=x11;
        - export DISPLAY=:99.0;
        - export PATH=$CMAKE_PATH:$PATH
        - export VULKAN_SDK="/c/VulkanSDK/$(ls /c/VulkanSDK/)"
        - mkdir build && cd build
        - cmake -G "Visual Studio 16 2019" ..
        - cmake --build .
        - ./testNeko/Debug/Neko_TEST.exe
        - ./testAer/Debug/Aer_TEST.exe

# Don't send notifications on success
notifications:
  email:
    on_success: never

